# Generated by Django 4.2.16 on 2026-06-23 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('plate', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('fleet', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('odometer', models.FloatField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'En Curso'), (2, 'Finalizada')])),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicle')),
            ],
        ),
    ]
